- hosts: Demo_Primary
  gather_facts: yes

  name: Set up Primary
  tasks:
    - name: Update Repositories and Install Bind9 and 
      ansible.builtin.apt:
        update_cache: yes
        pkg:
        - bind9
        - resolvconf

    - name: Create Demo Directory
      ansible.builtin.file:
        path: /etc/demo
        state: directory
        mode: '0755'

    - name: Generate the Templates and Move to Location
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - { src: ../templates/nodes.yaml.j2, dest: /etc/demo/nodes.yaml }
        - { src: ../templates/jobs.yaml.j2, dest: /etc/demo/jobs.yaml }

    - name: Modify nameserver to look at bind
      become: yes
      register: command_output
      lineinfile:
        path: /run/systemd/resolve/stub-resolv.conf
        regexp: "{{ item.from }}"
        line: "{{ item.to }}"
        state: present
      with_items:
        - { from: 'nameserver 127.0.0.53', to: 'nameserver 127.0.0.1' }

    # - name: Enable and Start Bind
    #   ansible.builtin.systemd:
    #     enabled: yes
    #     state: restarted
    #     name: {{ item }}
    #     daemon_reload: yes
    #   with_items:
    #     - "bind"
    #     - "systemd-resolved"
    #     - "resolvconf"