- hosts: Demo_Primary
  gather_facts: yes

  vars:
    demo_main_net: "{{ hostvars[groups['Demo_Primary'][0]]['ansible_facts']['default_ipv4'] }}"

  name: Set up Primary
  tasks:
    - name: Update Repositories and Install Bind9 and Resolvconf
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        pkg:
        - bind9
        - resolvconf

    - name: Create Demo Directory
      become: yes
      ansible.builtin.file:
        path: /etc/demo
        state: directory
        mode: '0755'

    - name: Generate the Templates and Move to Location
      become: yes
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - { src: ../templates/nodes.yaml.j2, dest: /etc/demo/nodes.yaml }
        - { src: ../templates/named.conf.options, dest: /etc/bind/named.conf.options }